[workspace]
members = [
    "hermit-abi",
    "hermit-sys",
    "benches/netbench",
    "benches/micro",
    "examples/hello_world",
    "examples/httpd",
    "examples/demo",
    "DeviceTree/device-tree"
]
exclude = ["target", "libhermit-rs"]
