[package]
name = "micro_benchmarks"
version = "0.1.0"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>"]
edition = "2021"
publish = false

[dependencies]
rayon = "1.5.2"

[target.'cfg(target_os = "hermit")'.dependencies.hermit-sys]
path = "../../hermit-sys"
default-features = false
features = ["acpi", "pci", "smp", "with_submodule"]

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = { version = "0.0.7", default-features = false }
tock-registers = "0.7"

[target.'cfg(target_os = "linux")'.dependencies]
syscalls = { version = "0.5", default-features = false }
